/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_orchestratorwasm_free: (a: number, b: number) => void;
export const orchestratorwasm_add_agent: (a: number, b: any) => any;
export const orchestratorwasm_add_project: (a: number, b: any) => any;
export const orchestratorwasm_add_shared_file: (a: number, b: any) => any;
export const orchestratorwasm_add_tool: (a: number, b: any) => any;
export const orchestratorwasm_configure_inference: (a: number, b: any) => [number, number];
export const orchestratorwasm_configure_rate_limits: (a: number, b: any) => [number, number];
export const orchestratorwasm_found_company: (a: number, b: number, c: number) => any;
export const orchestratorwasm_get_agent_context: (a: number, b: number, c: number) => [number, number, number];
export const orchestratorwasm_get_agent_memories: (a: number, b: number, c: number) => [number, number, number];
export const orchestratorwasm_get_agent_memory_tree: (a: number, b: number, c: number) => [number, number, number];
export const orchestratorwasm_get_agents: (a: number) => [number, number, number];
export const orchestratorwasm_get_company_name: (a: number) => [number, number];
export const orchestratorwasm_get_projects: (a: number) => [number, number, number];
export const orchestratorwasm_get_shared_files: (a: number) => [number, number, number];
export const orchestratorwasm_get_shared_tree: (a: number) => [number, number, number];
export const orchestratorwasm_get_tools: (a: number) => [number, number, number];
export const orchestratorwasm_init: () => any;
export const orchestratorwasm_remove_agent: (a: number, b: number, c: number) => any;
export const orchestratorwasm_remove_shared_file: (a: number, b: number, c: number) => any;
export const orchestratorwasm_remove_tool: (a: number, b: number, c: number) => any;
export const orchestratorwasm_run_orchestrator: (a: number) => any;
export const orchestratorwasm_send_agent_message: (a: number, b: number, c: number, d: number, e: number) => any;
export const orchestratorwasm_update_agent: (a: number, b: number, c: number, d: any) => any;
export const orchestratorwasm_update_tool: (a: number, b: number, c: number, d: any) => any;
export const wasm_bindgen_d05406a4d4dc2481___convert__closures_____invoke___js_sys_5b72c82c83b45550___Function_fn_wasm_bindgen_d05406a4d4dc2481___JsValue_____wasm_bindgen_d05406a4d4dc2481___sys__Undefined___js_sys_5b72c82c83b45550___Function_fn_wasm_bindgen_d05406a4d4dc2481___JsValue_____wasm_bindgen_d05406a4d4dc2481___sys__Undefined_______true_: (a: number, b: number, c: any, d: any) => void;
export const wasm_bindgen_d05406a4d4dc2481___convert__closures_____invoke___wasm_bindgen_d05406a4d4dc2481___JsValue__core_ed718c3d60ebd546___result__Result_____wasm_bindgen_d05406a4d4dc2481___JsError___true_: (a: number, b: number, c: any) => [number, number];
export const wasm_bindgen_d05406a4d4dc2481___convert__closures_____invoke_______true_: (a: number, b: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_destroy_closure: (a: number, b: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
